# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'write.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(367, 248)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtNodeId = QtWidgets.QTextEdit(self.centralwidget)
        self.txtNodeId.setGeometry(QtCore.QRect(110, 60, 71, 31))
        self.txtNodeId.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txtNodeId.setObjectName("txtNodeId")
        self.lblNodeId = QtWidgets.QLabel(self.centralwidget)
        self.lblNodeId.setGeometry(QtCore.QRect(20, 65, 58, 15))
        self.lblNodeId.setObjectName("lblNodeId")
        self.lblGroupId = QtWidgets.QLabel(self.centralwidget)
        self.lblGroupId.setGeometry(QtCore.QRect(20, 115, 58, 15))
        self.lblGroupId.setObjectName("lblGroupId")
        self.lblMemberNum = QtWidgets.QLabel(self.centralwidget)
        self.lblMemberNum.setGeometry(QtCore.QRect(20, 165, 91, 16))
        self.lblMemberNum.setObjectName("lblMemberNum")
        self.txtGroupId = QtWidgets.QTextEdit(self.centralwidget)
        self.txtGroupId.setGeometry(QtCore.QRect(110, 110, 71, 31))
        self.txtGroupId.setObjectName("txtGroupId")
        self.txtMemberNum = QtWidgets.QTextEdit(self.centralwidget)
        self.txtMemberNum.setGeometry(QtCore.QRect(110, 160, 71, 31))
        self.txtMemberNum.setObjectName("txtMemberNum")
        self.btnWrite = QtWidgets.QPushButton(self.centralwidget)
        self.btnWrite.setGeometry(QtCore.QRect(240, 60, 75, 23))
        self.btnWrite.setObjectName("btnWrite")
        self.lblPort = QtWidgets.QLabel(self.centralwidget)
        self.lblPort.setGeometry(QtCore.QRect(20, 20, 47, 12))
        self.lblPort.setObjectName("lblPort")
        self.cbPort = QtWidgets.QComboBox(self.centralwidget)
        self.cbPort.setGeometry(QtCore.QRect(110, 10, 201, 22))
        self.cbPort.setObjectName("cbPort")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 367, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EEPROM Write"))
        self.txtNodeId.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11.25pt;\">1</span></p></body></html>"))
        self.lblNodeId.setText(_translate("MainWindow", "Node Id:"))
        self.lblGroupId.setText(_translate("MainWindow", "Group Id:"))
        self.lblMemberNum.setText(_translate("MainWindow", "Member Num:"))
        self.txtGroupId.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11.25pt;\">1</span></p></body></html>"))
        self.txtMemberNum.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11.25pt;\">1</span></p></body></html>"))
        self.btnWrite.setText(_translate("MainWindow", "Write"))
        self.lblPort.setText(_translate("MainWindow", "Port:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
